### ISSUE TITLE
Persist logs

### ISSUE THREAD

**Issue by bickelj** [PhilanthropyDataCommons/deploy#56]
At the moment, there are logs, but they are contained in the container. When the containers go away, the logs go away.

**Comment by kfogel** [comment]
Some context: we need this because *if* someone asks for an audit trail of accesses, we need to be able to comply.  It's okay if we spend low effort now to save the data and higher effort later to gather all the information needed to respond to the request -- as long as the raw information is *there* for us to gather and format, we can make it work.  We just need to have saved the raw information in the first place.

Post-pilot, we could build better ways to save the access data, including including access logs as a first class element in the schema.  For the pilot, it's okay to keep things simple and just save logs.

See also [2022-11-30 OTS internal Zulip conversation about this](https://chat.opentechstrategies.com/#narrow/stream/66-PDC/topic/Data/near/151932).

**Comment by bickelj** [comment]
As it turns out, no simple log rotation is done using purely nginx configuration. It seems nginx expects another process either inside or outside the container. Inside is awkward because we would need to run cron inside and also that other process (instead of just nginx in the container). Outside is awkward because we currently run all the things in containers. There is probably a clever/simple approach that is least worst (other than a continuously growing log file).

**Comment by bickelj** [comment]
This is probably good enough: https://docs.docker.com/config/containers/logging/journald/

**Comment by bickelj** [comment]
I didn't see a way to distinguish `stderr` from `stdout` using the `journald` docker logging driver. That's probably OK for now as well. I configured larger limits for `journald ` on hosts by setting these in `/etc/systemd/journald.conf`:
```
SystemMaxUse=500G
SystemKeepFree=3G
```
I am not sure what happens for folks without `journald` (most of the world, I suppose) but I guess they could remove the lines added in #57. The primary use of these scripts is for the primary instance of PDC, which is currently a GNU/Linux machine that happens to run `journald`.
